"""article_ai_content

Revision ID: 02f1e1d40ac9
Revises: de8525da2919
Create Date: 2025-02-25 21:00:53.443624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02f1e1d40ac9'
down_revision = 'de8525da2919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('ai_abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('article', sa.Column('ai_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'ai_content')
    op.drop_column('article', 'ai_abstract')
    # ### end Alembic commands ###
