"""resource description  text

Revision ID: 34474b8525d1
Revises: 98e6a2464be1
Create Date: 2025-02-26 18:50:54.876901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34474b8525d1'
down_revision = '98e6a2464be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'description',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###
