"""article status

Revision ID: 51bd05df4700
Revises: 8ba6a7214504
Create Date: 2025-02-25 23:41:04.020685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51bd05df4700'
down_revision = '8ba6a7214504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('article', 'resoure_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=4024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'resoure_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=4024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('article', 'status')
    # ### end Alembic commands ###
