"""article  model url can be empty

Revision ID: 8ba6a7214504
Revises: 02f1e1d40ac9
Create Date: 2025-02-25 23:30:43.455814

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ba6a7214504'
down_revision = '02f1e1d40ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_url', table_name='article')
    op.create_index(op.f('ix_article_url'), 'article', ['url'], unique=False)
    op.create_index(op.f('ix_article_resoure_id'), 'article', ['resoure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_resoure_id'), table_name='article')
    op.drop_index(op.f('ix_article_url'), table_name='article')
    op.create_index('ix_article_url', 'article', ['url'], unique=True)
    # ### end Alembic commands ###
