"""resource_id

Revision ID: 98e6a2464be1
Revises: d07a9fecd920
Create Date: 2025-02-26 17:49:00.781920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '98e6a2464be1'
down_revision = 'd07a9fecd920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_article_resoure_id', table_name='article')
    op.create_index(op.f('ix_article_resource_id'), 'article', ['resource_id'], unique=False)
    op.drop_column('article', 'resoure_id')
    op.add_column('resource', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('resource', sa.Column('last_parse_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'last_parse_at')
    op.drop_column('resource', 'status')
    op.add_column('article', sa.Column('resoure_id', sa.VARCHAR(length=4024), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_article_resource_id'), table_name='article')
    op.create_index('ix_article_resoure_id', 'article', ['resoure_id'], unique=False)
    op.drop_column('article', 'resource_id')
    # ### end Alembic commands ###
