"""abstract 5000

Revision ID: adf50d869c74
Revises: fd4173c7b594
Create Date: 2025-02-26 15:45:39.720991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'adf50d869c74'
down_revision = 'fd4173c7b594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'abstract',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=5000),
               existing_nullable=True)
    op.alter_column('resource', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('article', 'abstract',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
