"""article description  text

Revision ID: b50cfb199e31
Revises: 34474b8525d1
Create Date: 2025-02-26 18:52:13.152588

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b50cfb199e31'
down_revision = '34474b8525d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'abstract',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('article', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('article', 'ai_abstract',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('article', 'ai_content',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'ai_content',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('article', 'ai_abstract',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('article', 'content',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('article', 'abstract',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###
