"""abstract no maxlength

Revision ID: d07a9fecd920
Revises: adf50d869c74
Create Date: 2025-02-26 15:54:13.977449

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd07a9fecd920'
down_revision = 'adf50d869c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
